name: Tests

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  test:
    name: Run tests
    runs-on: self-hosted
    container:
      image: ubuntu:latest
      env:
        DEB_PYTHON_INSTALL_LAYOUT: deb
        DEBIAN_FRONTEND: noninteractive
        TZ: Europe/Warsaw
      # Perhaps this could be hardened even more (and in oioioi's docker-compose too).
      options:
        # Epic.
        --security-opt seccomp:../../../../seccomp.json
        --cap-add ALL

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Install apt dependencies
        run: |
          apt-get update
          apt-get install -y libdb-dev fp-compiler fp-units-base fp-units-math gcc g++

      - name: Cache Python dependencies
        uses: actions/cache@v3
        env:
          cache-name: 'cache-pip'
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-dev-${{ env.cache-name }}-${{ inputs.python-version }}-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-dev-${{ env.cache-name }}-${{ inputs.python-version }}-${{ hashFiles('**/setup.py') }}
            ${{ runner.os }}-dev-${{ env.cache-name }}-${{ inputs.python-version }}-
            ${{ runner.os }}-dev-
            ${{ runner.os }}-

      - name: Install Python dependencies
        run: |
          pip3 install --user virtualenv
          python3 -m venv venv
          . venv/bin/activate
          pip3 install -e .[dev]

      - name: Run tests
        env:
          TEST_SANDBOXES: '0'
          NO_JAVA_TESTS: '1'
          NO_SIO2JAIL_TESTS: '0'
        run: |
          . venv/bin/activate
          pytest -v
