name: Tests

on:
  push:
    branches:
      - master
  #pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11']

    uses: './.github/workflows/tests-reusable.yml'
    with:
      python-version: ${{ matrix.python-version }}
